jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  numExecutors: 4
  scmCheckoutRetryCount: 2
  mode: NORMAL

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git
  nodejs:
    installations:
      - name: "nodejs"
        home: "/usr/local/nodejs"
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "20.11.0"

jobs:
  - script: >
      pipelineJob('UserServer') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url 'https://github.com/IDontHaveBrain/AutoClassification.git'
                          }
                      }
                  }
                  scriptPath 'UserServer/Jenkinsfile'
              }
          }
      }
  - script: >
      pipelineJob('UserFront') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url 'https://github.com/IDontHaveBrain/AutoClassification.git'
                          }
                      }
                  }
                  scriptPath 'front/Jenkinsfile'
              }
          }
      }