pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/IDontHaveBrain/AutoClassification.git'
                dir('UserServer') {
                    sh 'chmod +x gradlew'
                }
            }
        }

        stage('Build with Gradle') {
            steps {
                dir('UserServer') {
                    sh './gradlew build'
                    sh 'ls -la build/libs'
                }
            }
        }

        stage('Build Docker image') {
            steps {
                sh 'docker-compose build UserServer'
            }
        }

        stage('Run Docker image') {
            steps {
                sh 'docker-compose up -d UserServer'
            }
        }
    }
}