version: '3.8'
services:
  base-img:
    image: nobrain/base
    build:
      context: ./jdk-base
      dockerfile: Dockerfile

  redis:
    image: redis:alpine
    container_name: autoclassify-redis
    restart: always
    networks:
      - share-net
    volumes:
      - /data/docker/toy/redis:/data
      - /data/docker/toy/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6378:6379

  postgresql:
    image: postgres:alpine
    command: postgres -c 'max_connections=100'
    container_name: autoclassify_postgres
    restart: always
    volumes:
      - /data/docker/toy/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - share-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-jnj}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sqisoft}
      TZ: "Asia/Seoul"

  jenkins:
    container_name: autoclassify-jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    restart: always
    user: root
    #    networks:
    #      - share-net
    volumes:
      - /data/docker/toy/jenkins:/var/jenkins_home
      #        - /home/jenkins/.ssh:/jenkins/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker/toy/nginx/html:/usr/share/nginx/html
    ports:
      - 7080:7080
      - 50001:50000
    environment:
      TZ: "Asia/Seoul"
      CASC_JENKINS_CONFIG: /app/jenkins/casc_configs/jenkins.yaml
      JENKINS_OPTS: "--httpPort=7080"
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  nginx:
    container_name: autoclassify-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /data/docker/toy/nginx/log:/var/log/nginx
      - /data/docker/toy/nginx/html:/usr/share/nginx/html
    networks:
      - share-net
    expose:
      - 7081
    ports:
      - 8087:7081
    environment:
      TZ: "Asia/Seoul"

  rabbit:
    image: rabbitmq:management-alpine
    container_name: autoclassify-rabbit
    restart: always
    networks:
      - share-net
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
      TZ: "Asia/Seoul"

networks:
  share-net:
    external: true