version: '3'
services:

 UserServer:
  build:
   context: ./UserServer
   dockerfile: Dockerfile
  image: nobrain/user-server
  container_name: UserServer
  restart: always
  volumes:
   - /data/logs/UserServer:/var/log
  ports:
   - 8080:8080
  networks:
   - share-net
  environment:
   TZ: "Asia/Seoul"

networks:
 share-net:
  external: true
