version: '3'
services:
 UserServer:
  build:
   context: ./UserServer
   dockerfile: Dockerfile
  image: nobrain/user-server
  container_name: UserServer
  restart: always
  volumes:
   - /data/logs/UserServer:/var/log
   - /data/docker/toy:/data/docker/toy
  ports:
   - 8080:8080
  networks:
   - share-net
  environment:
   TZ: "Asia/Seoul"

 AiServer:
  build:
   context: ./AiServer
   dockerfile: Dockerfile
  image: nobrain/ai-server
  container_name: AiServer
  restart: always
  volumes:
   - /data/logs/AiServer:/var/log
  ports:
   - 5000:5000
  networks:
   - share-net
  environment:
   TZ: "Asia/Seoul"
   OPENAI_API_KEY: ${OPENAI_API_KEY}

networks:
 share-net:
  external: true
