version: '3'
services:
# base:
#  extends:
#   file: docker-env/docker-compose.yml
#   service: base-img

 UserServer:
#  depends_on:
#    - base
  build:
   context: ./UserServer
   dockerfile: Dockerfile
  image: nobrain/userserver
  container_name: UserServer
  restart: always
  volumes:
   - /data/logs/UserServer:/var/log
  ports:
   - 8080:8080
  networks:
   - inner-net
  environment:
   TZ: "Asia/Seoul"
