version: '3'
services:

 UserServer:
  build:
   context: ./UserServer
   dockerfile: Dockerfile
  image: nobrain/userserver
  container_name: UserServer
  restart: always
  volumes:
   - /data/logs/UserServer:/var/log
  ports:
   - 8080:8080
  networks:
   - shared-net
  environment:
   TZ: "Asia/Seoul"

networks:
 shared-net:
  external: true
