spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dev.nobrain.cc:5433/postgres
    username: postgres
    password: zktldk

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: dev.nobrain.cc
      port: 6379