spring:
  # 데이터베이스 설정 - TestContainers 동적 속성에 의해 재정의됨
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 35  # 배치 파일 처리를 위한 충분한 풀 크기 (12개 이미지 동시 처리)
      minimum-idle: 15  # Increased proportionally
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000  # 30 minutes
      leak-detection-threshold: 60000  # 60 seconds

  jpa:
    hibernate:
      ddl-auto: create-drop  # 각 테스트마다 스키마 재생성
    properties:
      hibernate:
        format_sql: false
        show_sql: false      # 테스트에서 SQL 로깅 비활성화
        jdbc:
          batch_size: 20     # 배치 처리 최적화
        order_inserts: true
        order_updates: true

  # Redis 설정 - TestContainers 동적 속성에 의해 재정의됨
  data:
    redis:
      timeout: 5000

  # RabbitMQ 설정 - TestContainers 동적 속성에 의해 재정의됨
  rabbitmq:
    listener:
      simple:
        concurrency: 15      # 증가된 테스트용 동시성 (12개 이미지 동시 처리)
        max-concurrency: 25  # Increased for concurrent processing
        prefetch: 3
    connection-timeout: 5000
    requested-heartbeat: 60
    cache:
      channel:
        size: 10             # 테스트용 작은 캐시 크기
        checkout-timeout: 10
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

  # 보안 설정 (테스트용 프로덕션과 동일)
  security:
    jwt:
      privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCphrH9+b4k1we/qpw9jGTxL6JbJOedFYLP8XPXty4adRVBf3ZAZV0sr7dSzhWA9r0V/jqeEM+5tHwVnjNzkuDBncdvegdnbJ1/vlyh3iNDXE2IzJtjq29tTkh6SL0TMMN4LQRLfL+x3ZwbDfe4ddgP2ssgm1dtnhpo0KcpY/FJQ7ED8A2uSuTxc7pvNvzwDnBmbD9gLHXSeo338qQgdG+sYupjeTElaVYum7Wxh0heFbo+7gWSL1S4GAXLMe+WyWoPPX1w5YYrSGASBv88WD30YfIOWtAHRx4EJa1yWeA2jYmrLIMKNAOgzhit7v+/NxGsIpdqDw2lzOy+2pfma91pAgMBAAECggEABtR1yZgVHm4Y4nKU2KB2RSbQhVhJahFeq7LMQl+/kGKQ9Ip2eM30qOsb6U7C/EcEk3UihrGB8vcH7EWLSF/dpQNOsImzsGmmd0nzuLRGyq0WdRlcNdHne3mEz0NstbAYYfg7VPC91uRJKKhhh3mc9rePiTzk8vZElV45q9/aTeOm003yEKz5izk2+579jRsaJlPxNGGBf0Z9tH3iPXUO0BZr5PNlnVfYRoKAJ8xxbH2nIK5SJHY0aCH0M50bOBKZDRsKzbfOYyVjrFZfLg1mc+Y+ksKBFRg/h4lzlkA8g9MuQJus4zEKKuc+zEv2IgLoPPKegb5B9h1RNijqwQHKYQKBgQDffZBY0+aiW/2IcRJJ9TtlBYnVMZKJnXusPRKTd8lqOue0+09VHqR7soYqM7dlKP2SrYCGVSQ7Y0DCXBlilIfIP8EzbkZHyn3ltxHiyDMzS31UT/FElyk9sbXX0GORGt2Z5txhlK0G586uzRyP9L7jNbkZzuPKCnybatJ9EdOjSQKBgQDCL5WKsJNVzFmcEPrJDVozUadH1yaeGAf8Qt8fG8xuyK669sUBwWBuljxJeMj4UFf592f2ovJdG3Tbav5v+jb0dTLH9HrmM4i/SxB/4JHsMtq0gPiYHhJymdKPWznG1KXoAbFwQsQL9l38l7p7uBepc/1p1yi5MLU6tBDvp/RJIQKBgEYPte2y2C1zyyI32DTpNOpxdwknljmf7gJLzwP93F16A+NfmTok9gl1KMwYFFkZJY0S6SSzkj0v20BS4P5fc8WZ/vYhjtS4rQkTf/7pJevhsXN58DfBb4NQr6HtSRlXI7s4fUP1+NweVVPFJzwVzLWrxNBLZGuVKAUM0tm0efVJAoGAPlszZS7gkRum5uPY9HjyLyqYUgx33SqQXeRHa+DsW+LboTQe/TpQshJSV7GOr5Z1OdLFssCOnXF0rAUGoYSy4vtDjEworwV7cxoyuS2vDi8iZfZIXejCOcTFhb1gp0Wf5QmuJgN6mvDJK5S5kIMELikOBk/ORvGqMKikC6FeY6ECgYANem9aZXoLqw0+OqwPvxt3LNLFASf2A+x2kM4V2BsUy8al0fizHOFKOOyNOuRoj5qwzJ0M4bUbc0BsXAijEHhPKvu+oNtVV9u/XA78JWZl+HXYwVWNmIB/DJk92VJb9dtK3PibKZbWDdqenEo6j0PqaDElBsLjrxa8F2ik8jli/A==
      signKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqYax/fm+JNcHv6qcPYxk8S+iWyTnnRWCz/Fz17cuGnUVQX92QGVdLK+3Us4VgPa9Ff46nhDPubR8FZ4zc5LgwZ3Hb3oHZ2ydf75cod4jQ1xNiMybY6tvbU5Ieki9EzDDeC0ES3y/sd2cGw33uHXYD9rLIJtXbZ4aaNCnKWPxSUOxA/ANrkrk8XO6bzb88A5wZmw/YCx10nqN9/KkIHRvrGLqY3kxJWlWLpu1sYdIXhW6Pu4Fki9UuBgFyzHvlslqDz19cOWGK0hgEgb/PFg99GHyDlrQB0ceBCWtclngNo2JqyyDCjQDoM4Yre7/vzcRrCKXag8NpczsvtqX5mvdaQIDAQAB
      accessTokenValiditySeconds: 86400  # 24시간
      refreshTokenValiditySeconds: 604800 # 7일

  # 메일 설정 (테스트용 비활성화)
  mail:
    test-connection: false

  # 파일 업로드 설정 (테스트용 - 12개 이미지 동시 처리 지원)
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 1GB  # 6 images * 200MB + overhead
      file-size-threshold: 10MB  # Write to disk after 10MB
      location: /tmp/uploads

# 테스트용 로깅 설정
logging:
  level:
    root: warn
    cc.nobrain.dev.userserver: info
    org.springframework.web: warn
    org.hibernate: warn
    org.springframework.amqp: warn
    org.testcontainers: info

# 테스트용 애플리케이션 설정
app:
  url:
    ai: ${AI_URL:http://localhost:5000}

  # 스토리지 설정 - DockerIntegrationTest에 의해 재정의됨
  storage:
    maxFileSize: 209715200  # 200MB

# 서버 설정 (테스트용 - 12개 이미지 동시 처리 지원)
server:
  tomcat:
    max-connections: 2000  # Increased from 1000 for concurrent testing
    accept-count: 100  # Increased from 50 for concurrent testing
    max-parameter-count: 50000
    max-http-form-post-size: 1GB  # Match max-request-size
    # Thread pool configuration for concurrent processing
    threads:
      max: 150  # Balanced for test environment
      min-spare: 10  # Standard for test
    # Connection management
    connection-timeout: 30000
    keep-alive-timeout: 30000
    max-keep-alive-requests: 100
    # Additional multipart limits
    max-swallow-size: 2GB

# 테스트용 관리 엔드포인트
management:
  endpoints:
    web:
      exposure:
        include: health,info