spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://autoclassify_postgres:5432/postgres
    username: ${DB_USERNAME:jnj}
    password: ${DB_PASSWORD:sqisoft}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # show_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  data:
    redis:
      host: autoclassify-redis
      port: 6379
      timeout: 5000

  rabbitmq:
    host: autoclassify-rabbit
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
    connection-timeout: 5000
    requested-heartbeat: 60
    cache:
      channel:
        size: 25
        checkout-timeout: 10
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

  security:
    jwt:
      privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCphrH9+b4k1we/qpw9jGTxL6JbJOedFYLP8XPXty4adRVBf3ZAZV0sr7dSzhWA9r0V/jqeEM+5tHwVnjNzkuDBncdvegdnbJ1/vlyh3iNDXE2IzJtjq29tTkh6SL0TMMN4LQRLfL+x3ZwbDfe4ddgP2ssgm1dtnhpo0KcpY/FJQ7ED8A2uSuTxc7pvNvzwDnBmbD9gLHXSeo338qQgdG+sYupjeTElaVYum7Wxh0heFbo+7gWSL1S4GAXLMe+WyWoPPX1w5YYrSGASBv88WD30YfIOWtAHRx4EJa1yWeA2jYmrLIMKNAOgzhit7v+/NxGsIpdqDw2lzOy+2pfma91pAgMBAAECggEABtR1yZgVHm4Y4nKU2KB2RSbQhVhJahFeq7LMQl+/kGKQ9Ip2eM30qOsb6U7C/EcEk3UihrGB8vcH7EWLSF/dpQNOsImzsGmmd0nzuLRGyq0WdRlcNdHne3mEz0NstbAYYfg7VPC91uRJKKhhh3mc9rePiTzk8vZElV45q9/aTeOm003yEKz5izk2+579jRsaJlPxNGGBf0Z9tH3iPXUO0BZr5PNlnVfYRoKAJ8xxbH2nIK5SJHY0aCH0M50bOBKZDRsKzbfOYyVjrFZfLg1mc+Y+ksKBFRg/h4lzlkA8g9MuQJus4zEKKuc+zEv2IgLoPPKegb5B9h1RNijqwQHKYQKBgQDffZBY0+aiW/2IcRJJ9TtlBYnVMZKJnXusPRKTd8lqOue0+09VHqR7soYqM7dlKP2SrYCGVSQ7Y0DCXBlilIfIP8EzbkZHyn3ltxHiyDMzS31UT/FElyk9sbXX0GORGt2Z5txhlK0G586uzRyP9L7jNbkZzuPKCnybatJ9EdOjSQKBgQDCL5WKsJNVzFmcEPrJDVozUadH1yaeGAf8Qt8fG8xuyK669sUBwWBuljxJeMj4UFf592f2ovJdG3Tbav5v+jb0dTLH9HrmM4i/SxB/4JHsMtq0gPiYHhJymdKPWznG1KXoAbFwQsQL9l38l7p7uBepc/1p1yi5MLU6tBDvp/RJIQKBgEYPte2y2C1zyyI32DTpNOpxdwknljmf7gJLzwP93F16A+NfmTok9gl1KMwYFFkZJY0S6SSzkj0v20BS4P5fc8WZ/vYhjtS4rQkTf/7pJevhsXN58DfBb4NQr6HtSRlXI7s4fUP1+NweVVPFJzwVzLWrxNBLZGuVKAUM0tm0efVJAoGAPlszZS7gkRum5uPY9HjyLyqYUgx33SqQXeRHa+DsW+LboTQe/TpQshJSV7GOr5Z1OdLFssCOnXF0rAUGoYSy4vtDjEworwV7cxoyuS2vDi8iZfZIXejCOcTFhb1gp0Wf5QmuJgN6mvDJK5S5kIMELikOBk/ORvGqMKikC6FeY6ECgYANem9aZXoLqw0+OqwPvxt3LNLFASf2A+x2kM4V2BsUy8al0fizHOFKOOyNOuRoj5qwzJ0M4bUbc0BsXAijEHhPKvu+oNtVV9u/XA78JWZl+HXYwVWNmIB/DJk92VJb9dtK3PibKZbWDdqenEo6j0PqaDElBsLjrxa8F2ik8jli/A==
      signKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqYax/fm+JNcHv6qcPYxk8S+iWyTnnRWCz/Fz17cuGnUVQX92QGVdLK+3Us4VgPa9Ff46nhDPubR8FZ4zc5LgwZ3Hb3oHZ2ydf75cod4jQ1xNiMybY6tvbU5Ieki9EzDDeC0ES3y/sd2cGw33uHXYD9rLIJtXbZ4aaNCnKWPxSUOxA/ANrkrk8XO6bzb88A5wZmw/YCx10nqN9/KkIHRvrGLqY3kxJWlWLpu1sYdIXhW6Pu4Fki9UuBgFyzHvlslqDz19cOWGK0hgEgb/PFg99GHyDlrQB0ceBCWtclngNo2JqyyDCjQDoM4Yre7/vzcRrCKXag8NpczsvtqX5mvdaQIDAQAB
      accessTokenValiditySeconds: 86400 # 24 hours
      refreshTokenValiditySeconds: 604800 # 7 days

  web:
    resources:
      static-locations:
        - file:C:/Work/test/

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:jonamjun.dev@gmail.com}
    password: ${MAIL_PASSWORD:xood lixw sfby ejqd}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: info
    cc.nobrain.dev.userserver: debug
    org.springframework.web: info
    org.hibernate: info
    cc.nobrain.dev.userserver.domain.sse: debug
    org.springframework.amqp: info

app:
  url:
    ai: http://localhost:5000

  storage:
    path: C:/Work/test/
    resourcePath: public/
    maxFileSize: 104857600


server:
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    max-connections: 10000
    accept-count: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
