spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://autoclassify_postgres:5433/postgres
    username: ${DB_USERNAME:jnj}
    password: ${DB_PASSWORD:sqisoft}
    hikari:
      maximum-pool-size: 40  # Increased for concurrent image processing
      minimum-idle: 20  # Increased proportionally
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000  # 30 minutes
      leak-detection-threshold: 60000  # 60 seconds

  data:
    redis:
      host: autoclassify-redis
      port: 6379
      timeout: 5000

  rabbitmq:
    host: autoclassify-rabbit
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        concurrency: 15  # Increased for concurrent processing
        max-concurrency: 25  # Increased for concurrent processing
        prefetch: 4

  mail:
    test-connection: false
    host: localhost
    port: 25
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 2GB  # 12 images * 200MB + overhead
      file-size-threshold: 10MB  # Write to disk after 10MB
      location: /tmp/uploads

  web:
    resources:
      static-locations:
        - file:/data/docker/toy/resource/public/
        - file:/data/docker/toy/resource/

management:
  health:
    mail:
      enabled: false
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  url:
    ai: ${AI_URL:http://localhost:5000}

  storage:
    path: /data/docker/toy/resource/
    resourcePath: public/
    maxFileSize: 209715200  # 200MB

server:
  tomcat:
    max-connections: 5000  # Increased from default 8192 (balanced for dev)
    accept-count: 150  # Increased from default 100
    max-parameter-count: 50000
    max-http-form-post-size: 2GB  # Match max-request-size
    # Thread pool configuration for concurrent processing
    threads:
      max: 250  # Increased from default 200
      min-spare: 15  # Increased from default 10
    # Connection management
    connection-timeout: 30000
    keep-alive-timeout: 30000
    max-keep-alive-requests: 100
    # Additional multipart limits
    max-swallow-size: 2GB

