spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://autoclassify_postgres:5432/postgres
    username: ${DB_USERNAME:jnj}
    password: ${DB_PASSWORD:sqisoft}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 30000

  data:
    redis:
      host: autoclassify-redis
      port: 6379
      timeout: 5000

  rabbitmq:
    host: autoclassify-rabbit
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  mail:
    test-connection: false
    host: localhost
    port: 25
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

  web:
    resources:
      static-locations:
        - file:/data/docker/toy/resource/public/
        - file:/data/docker/toy/resource/

management:
  health:
    mail:
      enabled: false
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

app:
  url:
    ai: http://localhost:5000

  storage:
    path: /data/docker/toy/resource/
    resourcePath: public/
    maxFileSize: 104857600

