spring:
  web:
    resources:
      static-locations:
        - file:/data/docker/toy/resource/

app:
  url:
    ai: http://AiServer:5000

  storage:
    path: /data/docker/toy/resource/
    resourcePath: public/
    maxFileSize: 10485760

jasypt:
  encryptor:
    password: testKey
