spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://autoclassify_postgres:5433/postgres
    username: ${DB_USERNAME:jnj}
    password: ${DB_PASSWORD:sqisoft}
    hikari:
      maximum-pool-size: 40  # 동시 이미지 처리를 위한 증가된 풀 크기
      minimum-idle: 20  # 풀 크기에 비례하여 증가
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000  # 30분
      leak-detection-threshold: 60000  # 60초

  data:
    redis:
      host: autoclassify-redis
      port: 6379
      timeout: 5000

  rabbitmq:
    host: autoclassify-rabbit
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        concurrency: 15  # 동시 처리를 위한 증가된 동시성
        max-concurrency: 25  # 동시 처리를 위한 최대 동시성
        prefetch: 4

  mail:
    test-connection: false
    host: localhost
    port: 25
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 1GB  # 6개 이미지 * 200MB + 오버헤드
      file-size-threshold: 10MB  # 10MB 이후 디스크에 쓰기
      location: /tmp/uploads

  web:
    resources:
      static-locations:
        - file:/data/docker/toy/resource/public/
        - file:/data/docker/toy/resource/

management:
  health:
    mail:
      enabled: false
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  url:
    ai: ${AI_URL:http://localhost:5000}

  storage:
    path: /data/docker/toy/resource/
    resourcePath: public/
    maxFileSize: 209715200  # 200MB

server:
  tomcat:
    max-connections: 5000  # 개발용으로 기본값 8192에서 증가 (균형잡힌 값)
    accept-count: 150  # 기본값 100에서 증가
    max-parameter-count: 50000
    max-http-form-post-size: 1GB  # max-request-size와 맞춤
    # 동시 처리를 위한 스레드 풀 설정
    threads:
      max: 250  # 기본값 200에서 증가
      min-spare: 15  # 기본값 10에서 증가
    # 연결 관리
    connection-timeout: 30000
    keep-alive-timeout: 30000
    max-keep-alive-requests: 100
    # 추가 multipart 제한
    max-swallow-size: 2GB

