version: '3'
services:
  base-img:
    image: nobrain/base
    build:
      context: ./jdk-base
      dockerfile: Dockerfile

  redis:
    image: redis:alpine
    container_name: autoclassify-redis
    restart: always
    networks:
      - shared-net
    volumes:
      - /data/docker/redis:/data
      - /data/docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  postgresql:
    image: postgres:alpine
    command: postgres -c 'max_connections=100'
    container_name: autoclassify_postgres
    restart: always
    volumes:
      - /data/docker/nobrain_postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - shared-net
    environment:
      POSTGRES_USER: "eliga_test"
      POSTGRES_PASSWORD: "Sqi2@24"
      TZ: "Asia/Seoul"

  jenkins:
    container_name: autoclassify-jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    restart: always
    user: root
#    networks:
#      - shared-net
    volumes:
        - /data/docker/jenkins:/var/jenkins_home
#        - /home/jenkins/.ssh:/jenkins/.ssh
        - /var/run/docker.sock:/var/run/docker.sock
        - /data/docker/nginx/html:/usr/share/nginx/html
    ports:
      - 8088:8088
      - 50000:50000
    environment:
      TZ: "Asia/Seoul"
      CASC_JENKINS_CONFIG: /app/jenkins/casc_configs/jenkins.yaml
      JENKINS_OPTS: "--httpPort=8088"

  nginx:
    container_name: autoclassify-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /data/docker/nginx/log:/var/log/nginx
      - /data/docker/nginx/html:/usr/share/nginx/html
    networks:
      - shared-net
    expose:
      - 8087
#    ports:
#      - 8087:8087
    environment:
      TZ: "Asia/Seoul"

networks:
  shared-net:
    external: true