pipeline {
    agent any

//     triggers {
//         GenericTrigger(
//             genericVariables: [
//                 [key: 'ref', value: '$.ref'],
//                 [key: 'target', value: '$.data.target']
//             ],
//             token: 'asd',
//             causeString: 'Triggered on $ref',
//             regexpFilterText: '$ref $target',
//             regexpFilterExpression: 'refs/heads/main userFe',
//             printContributedVariables: true,
//             printPostContent: true
//         )
//     }

    environment {
            FRONT_SRC_DIR = 'front'
        }

    tools {
        nodejs 'nodejs'
    }

    stages {
        stage('Setup') {
            steps {
                sh 'npm install -g yarn'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir(FRONT_SRC_DIR) {
                    sh 'yarn install'
                }
            }
        }

        stage('Build') {
            steps {
                dir(FRONT_SRC_DIR) {
                    sh 'yarn build'
                }
            }
        }

        stage('Copy Built Files') {
            steps {
                sh '''
                    mkdir -p /usr/share/nginx/html
                    cp -r front/build/* /usr/share/nginx/html/
                '''
            }
        }
    }
}
