name: 'AiServer Build Test'

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: 'AiServer Build Test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r ./AiServer/requirements.txt

      - name: Make AiServer executable
        run: chmod +x ./AiServer/app.py

      - name: Start AiServer and perform health check
        run: |
          python ./AiServer/app.py > server.log 2>&1 &
          SERVER_PID=$!
          while ! grep -q "Running on" server.log; do sleep 1; done
          curl http://localhost:5000/health
          kill $SERVER_PID

      - if: github.ref == 'refs/heads/main'
        name: 'Deploy'
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          data: '{ "target": "${{ secrets.AITARGET }}" }'
          webhook_type: 'json-extended'
          verbose: true
          verify_ssl: false
