jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  numExecutors: 4
  scmCheckoutRetryCount: 2
  mode: NORMAL

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: slack
              secret: '${SLACK_TOKEN}'

unclassified:
  slackNotifier:
    teamDomain: autoclassification
    tokenCredentialId: slack
    room: '#젠킨스-로그'

security:
  githooks:
    allowedOnAgents: true
    allowedOnController: true

tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git
  nodejs:
    installations:
      - name: "nodejs"
        home: "/usr/local/nodejs"
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "20.15.1"
  jdk:
    installations:
      - name: "jdk21"
        home: ""
        properties:
          - installSource:
              installers:
                - jdkInstaller:
                    id: "jdk-21"

jobs:
  - script: >
      pipelineJob('UserServer') {
          triggers {
              genericTrigger {
                  genericVariables {
                      genericVariable {
                          key 'ref'
                          value '\$.ref'
                      }
                      genericVariable {
                          key 'target'
                          value '\$.data.target'
                      }
                  }
                  token('asd')
                  printContributedVariables(true)
                  printPostContent(true)
                  regexpFilterText '\$ref \$target'
                  regexpFilterExpression 'refs/heads/main userBe'
              }
          }
          
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url 'https://github.com/IDontHaveBrain/AutoClassification.git'
                          }
                      }
                  }
                  scriptPath 'UserServer/Jenkinsfile'
              }
          }
      }
  - script: >
      pipelineJob('UserFront') {
          triggers {
              genericTrigger {
                  genericVariables {
                      genericVariable {
                          key 'ref'
                          value '\$.ref'
                      }
                      genericVariable {
                          key 'target'
                          value '\$.data.target'
                      }
                  }
                  token('asd')
                  printContributedVariables(true)
                  printPostContent(true)
                  regexpFilterText '\$ref \$target'
                  regexpFilterExpression 'refs/heads/main userFe'
              }
          }
      
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url 'https://github.com/IDontHaveBrain/AutoClassification.git'
                          }
                      }
                  }
                  scriptPath 'front/Jenkinsfile'
              }
          }
      }

  - script: >
      pipelineJob('AiServer') {
      triggers {
        genericTrigger {
            genericVariables {
                genericVariable {
                    key 'ref'
                    value '\$.ref'
                }
                genericVariable {
                    key 'target'
                    value '\$.data.target'
                }
            }
            token('asd')
            printContributedVariables(true)
            printPostContent(true)
            regexpFilterText '\$ref \$target'
            regexpFilterExpression 'refs/heads/main aiBe'
        }
      }
      
      definition {
          cpsScm {
              scm {
                  git {
                      remote {
                          url 'https://github.com/IDontHaveBrain/AutoClassification.git'
                      }
                  }
              }
              scriptPath 'AiServer/Jenkinsfile'
          }
          }
      }
